version: "3.8"
services:

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend_network
    volumes:
      - postgres_data:${POSTGRES_PGDATA}
      - ./config/postgresql.conf:/var/lib/postgresql/postgresql.conf

  pgadmin4:
    image: dpage/pgadmin4:6
    container_name: pgadmin4
    restart: always
    env_file: .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@gmail.com
    ports:
      - "${PGADMIN_ADDRESS}:${PGADMIN_PORT}:80"
    networks:
      - backend_network
    depends_on:
      - postgres_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./storage:/var/lib/pgadmin/storage/user_gmail.com

networks:
  backend_network:


volumes:
  postgres_data:
  pgadmin_data:
